version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                uid: "1000"
                user: "moustapha"
        container_name: "app"
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - "./:/var/www/html:cached"
        networks:
            - local-network

    webserver:
        image: nginx:stable-alpine
        container_name: "webserver"
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - "./:/var/www/html"
            - "./docker/nginx:/etc/nginx/conf.d"
        networks:
            - local-network
        depends_on:
            - app

networks:
    local-network:
        driver: bridge
